//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public System.Guid ID { get; set; }
        public string UserID { get; set; }
        public string Filename { get; set; }
        public string FileExtension { get; set; }
        public string BlobUrl { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
